### ISSUE TITLE
Cannot set a field to `None` when doing an item update

### ISSUE THREAD

**Issue by cb372** [guardian/scanamo#62]
```
    table.update(
      'id -> recipe.id,
      set('bakeSchedule -> bakeSchedule) // bakeSchedule == None
    )
```

fails with:

```
com.amazonaws.AmazonServiceException: Invalid UpdateExpression: An expression attribute value used in expression is not defined; attribute value: :r_update (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: PMVV1B4SD4DPG6KBAOUU2JJDPVVV4KQNSO5AEMVJF66Q9ASUAAJG)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1370)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:917)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:695)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:447)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:409)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:358)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2051)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2021)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:1848)
        at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:74)
        at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:49)
```

Aside: If Scanamo had support for `REMOVE` then I could work around this like so:

```
    table.update(
      'id -> recipe.id,
      if (bakeSchedule.isDefined) set('bakeSchedule -> bakeSchedule) else remove('bakeSchedule)
    )
```

I'll try and put together a PR to support `REMOVE`.

**Comment by cb372** [comment]
Added the necessary support for a workaround in #63
